# ICS 3202 - Semester Project Deliverable 1
## Dataset Exploration: Financial Transactions Dataset (Expenses & Income)

**Project idea:** Financial mobile application with an AI advisor that helps users track and understand their spending.

**Dataset:** [Financial Transactions Dataset (Expenses & Income)](https://www.kaggle.com/datasets/artemkabseu/financial-transactions-dataset-expenses-and-income) (Kaggle) — anonymized personal transaction records exported from a mobile finance tracking app.

The dataset ships as two files: `Expenses_clean.csv` and `Income_clean.csv`. For this deliverable we selected **`Expenses_clean.csv`** as the most appropriate one to explore

## Setup: load the dataset

In Colab, upload `Expenses_clean.csv` when prompted (click the folder icon on the left → upload, or run the cell below and use the file picker).

In [ ]:
import pandas as pd
df = pd.read_csv("Expenses_clean.csv")
df.head()

             date_time          category account  amount currency   tags
0  2025-11-30 00:00:00            Health  acct_1   114.0      BYN  tag_1
1  2025-11-29 00:00:00              Food  acct_1     5.0      BYN  tag_1
2  2025-11-27 00:00:00  Public transport  acct_2     1.0      BYN  tag_1
3  2025-11-27 00:00:00              Cafe  acct_1    10.0      BYN  tag_1
4  2025-11-27 00:00:00  Public transport  acct_2     1.0      BYN  tag_1

## a. How many rows and columns are contained in the dataset?

In [2]:
rows, columns = df.shape
print(f"Number of rows: {rows}")
print(f"Number of columns: {columns}")

Number of rows: 938
Number of columns: 6

## b. What datatypes are contained in the dataset? (3 marks)

In [3]:
df.dtypes

date_time        str
category         str
account          str
amount       float64
currency         str
tags             str
dtype: object

## c. Is the dataset complete?  no missing values?

In [4]:
missing_values = df.isnull().sum()
print(missing_values)

total_missing = missing_values.sum()
if total_missing == 0:
    print("\nThe dataset is complete: no missing values found.")
else:
    print(f"\nThe dataset is NOT complete: {total_missing} missing values found across the columns above.")

date_time    0
category     0
account      0
amount       0
currency     0
tags         0
dtype: int64

The dataset is complete: no missing values found.

## d. Slice out the first 15 rows and last 20 rows, merge into `df_sample`, and display it

In [5]:
first_15 = df.head(15)
last_20 = df.tail(20)

df_sample = pd.concat([first_15, last_20])
df_sample

               date_time          category account  amount currency   tags
0    2025-11-30 00:00:00            Health  acct_1   114.0      BYN  tag_1
1    2025-11-29 00:00:00              Food  acct_1     5.0      BYN  tag_1
2    2025-11-27 00:00:00  Public transport  acct_2     1.0      BYN  tag_1
3    2025-11-27 00:00:00              Cafe  acct_1    10.0      BYN  tag_1
4    2025-11-27 00:00:00  Public transport  acct_2     1.0      BYN  tag_1
5    2025-11-26 00:00:00              Cafe  acct_3     2.0      BYN  tag_1
6    2025-11-26 00:00:00  Public transport  acct_2     1.0      BYN  tag_1
7    2025-11-25 00:00:00  Public transport  acct_2     1.0      BYN  tag_1
8    2025-11-25 00:00:00  Public transport  acct_2     1.0      BYN  tag_1
9    2025-11-25 00:00:00              Cafe  acct_1    11.0      BYN  tag_1
10   2025-11-25 00:00:00              Taxi  acct_1    18.0      BYN  tag_1
11   2025-11-24 00:00:00              Food  acct_1     9.0      BYN  tag_1
12   2025-11-24 00:00:00  Public transport  acct_2     1.0      BYN  tag_1
13   2025-11-24 00:00:00  Public transport  acct_2     1.0      BYN  tag_1
14   2025-11-24 00:00:00              Cafe  acct_3     4.0      BYN  tag_1
918  2025-01-16 00:00:00  Public transport  acct_2     1.0      BYN  tag_3
919  2025-01-16 00:00:00              Taxi  acct_3    10.0      BYN  tag_1
920  2025-01-15 00:00:00  Public transport  acct_2     1.0      BYN  tag_4
921  2025-01-15 00:00:00  Public transport  acct_2     1.0      BYN  tag_4
922  2025-01-15 00:00:00  Public transport  acct_2     1.0      BYN  tag_2
923  2025-01-15 00:00:00              Food  acct_3     2.0      BYN  tag_1
924  2025-01-15 00:00:00  Public transport  acct_2     1.0      BYN  tag_2
925  2025-01-15 00:00:00  Public transport  acct_2     1.0      BYN  tag_3
926  2025-01-14 00:00:00  Public transport  acct_2     1.0      BYN  tag_3
927  2025-01-13 00:00:00              Food  acct_3     1.0      BYN  tag_1
928  2025-01-13 00:00:00              Food  acct_1    13.0      BYN  tag_1
929  2025-01-13 00:00:00  Public transport  acct_2     1.0      BYN  tag_6
930  2025-01-13 00:00:00  Public transport  acct_2     1.0      BYN  tag_4
931  2025-01-12 00:00:00             Other  acct_3    70.0      BYN  tag_1
932  2025-01-11 00:00:00              Food  acct_3     6.0      BYN  tag_1
933  2025-01-10 00:00:00  Public transport  acct_2     1.0      BYN  tag_2
934  2025-01-10 00:00:00  Public transport  acct_2     1.0      BYN  tag_2
935  2025-01-09 00:00:00              Taxi  acct_1    14.0      BYN  tag_1
936  2025-01-08 00:00:00              Taxi  acct_1    15.0      BYN  tag_1
937  2025-01-07 00:00:00              Food  acct_1     5.0      BYN  tag_1